    def _rxSensorData(self):
        # rxData = self.serial_port.read(64)
        # Alt method to read serial data
        rxData = self.serial_port.readline()
        rxDataGPSLat = struct.unpack('f', rxData[0:4])
        rxDataGPSLon = struct.unpack('f', rxData[4:8])
        rxDataGPSAlt = struct.unpack('f', rxData[8:12])
        rxDataAccelX = struct.unpack('f', rxData[12:16])
        rxDataAccelY = struct.unpack('f', rxData[16:20])
        rxDataAccelZ = struct.unpack('f', rxData[20:24])
        rxDataGyroX  = struct.unpack('f', rxData[24:28])
        rxDataGyroY  = struct.unpack('f', rxData[28:32])
        rxDataGyroZ  = struct.unpack('f', rxData[32:36])
        rxDataEulerI = struct.unpack('f', rxData[36:40])
        rxDataEulerJ = struct.unpack('f', rxData[40:44])
        rxDataEulerK = struct.unpack('f', rxData[44:48])
        
        # rxDataStr = rxData.decode('utf-8').strip()
        # Grab specfic data from the sensors for each metric
        # For now, just print out data that is being sent to the console:
        self._log(f"Received Sensor Data: {rxData}")
        # self._log(f"Received Sensor Data as Floats: {rxDataFloat}")
        # self._log(f"Received Sensor Data as Floats: {rxDataFloat2}")
        self.telemetryAccelXVar.set(rxDataAccelX)
        self.telemetryAccelYVar.set(rxDataAccelY)
        self.telemetryAccelZVar.set(rxDataAccelZ)
        self.telemetryGyroRollVar.set(rxDataGyroX)
        self.telemetryGyroYawVar.set(rxDataGyroY)
        self.telemetryGyroPitchVar.set(rxDataGyroZ)
        self.telemetryGPSLatVar.set(rxDataGPSLat)
        self.telemetryGPSLonVar.set(rxDataGPSLon)
        self.telemetryGPSAltVar.set(rxDataGPSAlt)
        self.telemetryEulerIVar.set(rxDataEulerI)
        self.telemetryEulerKVar.set(rxDataEulerJ)
        self.telemetryEulerJVar.set(rxDataEulerK)